### ISSUE TITLE
Unique ID on IOS?

### ISSUE THREAD

**Issue by winstef** [Paldom/UniqueDeviceID#6]
Hi,

After reading that the uuid on iOS is not unique to a device using the  apache cordova device plugin, I was wondering if your plugin was different from it? 
How does it work with iOS? is it a unique ID that I can rely on?

Thank you.

**Comment by Paldom** [comment]
Hi @winstef,
sorry for late response, hope I can still help. Since iOS 7, the device ID is not available on iOS platform, but this plugin uses a different solution: an unique ID is automatically generated before the first use and is saved to the device keychain. This UUID remains the same after app uninstall, system update etc.

**Comment by winstef** [comment]
Hey,

Thank you for help, it seems to be working fine on Android and iOS.
